#ifndef DATASTAX_INTERNAL_DRIVER_CONFIG_HPP
#define DATASTAX_INTERNAL_DRIVER_CONFIG_HPP

#define HAVE_KERBEROS
#define HAVE_OPENSSL
#define HAVE_STD_ATOMIC
#define CASS_CPP_STANDARD 11
/* #undef HAVE_BOOST_ATOMIC */
/* #undef HAVE_NOSIGPIPE */
#define HAVE_SIGTIMEDWAIT
/* #undef HASH_IN_TR1 */
#define HAVE_BUILTIN_BSWAP32
/* #undef HAVE_BUILTIN_BSWAP64 */
/* #undef HAVE_ARC4RANDOM */
#define HAVE_GETRANDOM
#define HAVE_TIMERFD
#define HAVE_ZLIB

#endif
